### ISSUE TITLE
Combining multiple files does not work

### ISSUE THREAD

**Issue by genomematt** [genomematt/pebbles#3]
Traceback (most recent call last):
  File "/Users/wakefield/PycharmProjects/CountESS/countess/core/pipeline.py", line 53, in execute
    self.result = self.plugin.run(input_data, logger, row_limit)
  File "/Users/wakefield/PycharmProjects/CountESS/countess/core/plugins.py", line 176, in run
    df = self.load_files(logger, row_limit)
  File "/Users/wakefield/PycharmProjects/CountESS/countess/core/plugins.py", line 301, in load_files
    callback(num_files, num_files + 1, "Combining")
NameError: name 'callback' is not defined

**Comment by nickzoic** [comment]
G'day Matt, there's been some API changes around how the plugins get called, basically I've replaced the "callback" function with a "logger" instance which is a little more flexible, the good thing is this helps resolve your #4 because plugins can now have warnings as well as errors, and they'll appear in a useful place in the GUI rather than getting lost in stderr.  I've got to write up an updated "how to write a plugin" doc to catch up with these changes.  Once we get to 0.1.0 I'll try not to break the plugin API all the time :-(

**Comment by genomematt** [comment]
Fixed in dev0.3 branch
